version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "9999:9999"
